title = "The Skeletor Project"
MetaDataFormat = "yaml"
pluralizeListTitles = false
theme = "skeletor"

[blackfriday]
  plainIDAnchors = true

[params]
  description = "Documentation of Hugo, a fast and flexible static site generator built with love by spf13, bep and friends in Go"
  author = "Steve Francia (spf13) and friends"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "About Skeletor"
    identifier = "about"
    pre = ""
    weight = -110
[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = ""
    weight = -100
[[menu.main]]
    name = "Development"
    identifier = "development"
    pre = ""
    weight = -90
[[menu.main]]
    name = "Components"
    identifier = "components"
    pre = ""
    weight = -80
[[menu.main]]
    name = "Contributing"
    identifier = "contribute"
    pre = ""
    weight = -60