title = "The Skeletor Project"
MetaDataFormat = "yaml"
pluralizeListTitles = false
theme = "skeletor"

[blackfriday]
  plainIDAnchors = true

[params]
  description = "Skeletor Documentation"
  author = "Delphic Digital"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "About Skeletor"
    identifier = "about"
    pre = ""
    weight = -110
[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = ""
    weight = -100
[[menu.main]]
    name = "Development"
    identifier = "development"
    pre = ""
    weight = -90
[[menu.main]]
    name = "Plugins"
    identifier = "plugins"
    pre = ""
    weight = -80
[[menu.main]]
    name = "Contributing"
    identifier = "contribute"
    pre = ""
    weight = -60
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = ""
    weight = -50
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = ""
    weight = -40